<?php
/**
 * @author    Militree
 * @category  design
 * @package   base_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license   http://www.magento.com/license/enterprise-edition
 */

/**
 * Product media data template
 *
 * @var Mage_Catalog_Block_Product_View_Media $this
 */

/* @parent_refrence "product.info" */
/* @var $this Mage_Catalog_Block_Product_View_Media */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');

    $_images = array();

    $_mainImageUrl = $this->helper('catalog/image')->init($_product, 'image')->keepFrame(false)->constrainOnly(true);
    $_images['main'] = new Varien_Object([
        'gallery_image_url' => $_mainImageUrl,
        'is_gallery_image_visible' => true,
        'file' => $_product->getImage(),
    ]);

    foreach ($this->getGalleryImages() as $_image) {
        if ($_image->getFile() != $_product->getImage()) {
            // This will index them starting at 0.
            $_image->setIsGalleryImageVisible($this->isGalleryImageVisible($_image));
            $_image->setGalleryImageUrl($this->getGalleryImageUrl($_image));
            $_images[] = $_image;
        }
    }
?>

<div id="flexslider" class="flexslider" tabindex="0">
    <ul class="slides product-image-gallery">
        <?php foreach ($_images as $i => $_image): ?>
            <?php if ($_image->getIsGalleryImageVisible()): ?>
                <?php /** @var Mage_Catalog_Helper_Image $helperImage */ ?>
                <?php $helperImage = $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->keepFrame(false)->constrainOnly(true); ?>
                <li>
                    <img id="image-<?php echo $i; ?>"
                         class="gallery-image lazyload"
                         src="<?php echo $helperImage->setQuality(16)->resize(720); ?>"
                         data-srcset="
                            <?php echo $helperImage->setQuality(80)->resize(320); ?> 320w,
                            <?php echo $helperImage->setQuality(80)->resize(720); ?> 720w,
                            <?php echo $helperImage->setQuality(80)->resize(920); ?> 920w,
                            <?php echo $helperImage->setQuality(80)->resize(1400); ?> 1400w
                         "
                         data-sizes="auto"
                         data-image-size="<?php echo ($helperImage->getOriginalWidth() * $helperImage->getOriginalHeight()) ?>"
                         data-zoom-image="<?php echo $_image->getGalleryImageUrl(); ?>" />
                 </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>

<?php echo $this->getChildHtml('after'); ?>
