
<?php
// var_dump($this->getJsonImageConfig());
die('wert');
?>

<script>
console.log('bada boom');////////////////////////////////////////////////////////////////////////////////////////// console.log Right Here ////////////////////////////////
    // (function() {

    // })
    // $(document).on('product-media-loaded', function() {
    // ConfigurableMediaImages.init('<?php echo $this->getImageType(); ?>');
    // ConfigurableMediaImages.imagesCollection = {};
    // <?php foreach () ?>
    // $(document).trigger('configurable-media-images-init', ConfigurableMediaImages);

    //     ConfigurableMediaImages.init('<?php echo $this->getImageType(); ?>');
    //     <?php foreach ($this->getProductImageFallbacks() as $imageFallback): ?>
    //       ConfigurableMediaImages.setImageFallback(
    //         <?php echo $imageFallback['product']->getId(); ?>,
    //         $j.parseJSON('<?php echo $imageFallback['image_fallback']; ?>')
    //       );
    //     <?php endforeach; ?>
    //     
    });
</script>


